# Generated by Django 3.2 on 2022-04-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='setlist.gig')),
                ('song', models.ManyToManyField(to='setlist.Song')),
            ],
        ),
    ]
