# Generated by Django 3.2 on 2022-04-27 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setlist', '0002_setlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setlist_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setlist',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting Confirmation'), (1, 'Published')], default=0),
        ),
    ]
