# Generated by Django 3.2 on 2022-04-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setlist', '0005_auto_20220427_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='gig',
        ),
        migrations.AddField(
            model_name='gig',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setlist.venue'),
        ),
    ]
